name: music_player
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  assets_audio_player: ^3.0.5
  sleek_circular_slider: ^2.0.1
  palette_generator: ^0.3.3+2
  on_audio_query: ^2.6.1
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Chillax
      fonts:
        - asset: assets/fonts/Chillax-Regular.otf
        - asset: assets/fonts/Chillax-SemiBold.otf
          weight: 600
          style: normal
        - asset: assets/fonts/Chillax-Medium.otf
          weight: 500
          style: normal
        - asset: assets/fonts/Chillax-Bold.otf
          weight: 400
          style: normal
        - asset: assets/fonts/Chillax-Light.otf
          weight: 300
          style: normal
        - asset: assets/fonts/Chillax-ExtraLight.otf
          weight: 200
          style: normal
